if (file_exists("SaveNew.sav")) file_delete("SaveNew.sav");
ini_open("SaveNew.sav");
var SavedRoom = room_loadingset;
ini_write_real("Save1","room",SavedRoom);
ini_write_real("Save1","xLocation",96);
ini_write_real("Save1","yLocation",640);
ini_write_real("Save1","points",global.points);
ini_close();
global.playerIsAlive = 1;
global.playerHp = 18;
global.keyObtained = 0;
global.holyWater = 0;
global.holyWaterMax = 0;
scr_loadgame();
